# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wommy
tagline:             'a Blog built with Jekyll, Lanyon, and Prose'
description:         'a Blog built for and by <a href="http://github.com/wommy" target="_blank">Wommy</a>, with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>, & <a href="http://prose.io" target="_blank">Prose</a>'
url:                 http://wommy.github.io/jekyll-lanyon
baseurl:             http://wommy.github.io/jekyll-lanyon
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

github:
  repo:  https://github.com/wommy/jekyll-lanyon

# Custom vars
version:             1.0.0

# prose
prose:
  siteurl: 'http://wommy.github.io/jekyll-lanyon/'
  ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
    - atom.xml
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
