# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             http://wommy.github.io/jekyll-lanyon
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

github:
  repo:  https://github.com/wommy/jekyll-lanyon

# Custom vars
version:             1.0.0

# prose
prose:
  siteurl: 'http://wommy.github.io/jekyll-lanyon/'
  ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
    - atom.xml
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
