# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:categories/:year/:title/
relative_permalinks: true

# Setup
url:                 http://wommy.github.io/
baseurl:             jekyll-lanyon/
# paginate
# paginate:            5
# paginate_path:       /:num/

# Site Specifics
title:               Wommy
tagline:             'a place for my digital stuff'

# About/contact
author:
  name:              Tommy Williams
  url:               https://twitter.com/froggie92
  email:             tom@technomad.media

github:
  repo:  https://github.com/wommy/jekyll-lanyon/
  version:             1.0.0

# prose
prose:
  siteurl: 'http://wommy.github.io/jekyll-lanyon/'
  ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
    - atom.xml
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    pages:
      - name: "layout"
        field:
          value: "page"
      - name: "permalink"
        field:
          value: "/{{page.title}}/"
